#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"
import { glob } from "glob" /*costrict change*/

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

/*costrict change start*/
// Build app first to ensure static assets are available
console.debug("Building app...")
const appDir = path.resolve(dir, "../app")
const appDistDir = path.join(appDir, "dist")

// Check if app needs to be built
let needsAppBuild = false
try {
  const distStats = await fs.promises.stat(appDistDir)
  if (!distStats.isDirectory()) {
    needsAppBuild = true
  }
} catch {
  needsAppBuild = true
}

if (needsAppBuild) {
  console.debug("App dist not found, building...")
  await $`cd ${appDir} && bun run build`
} else {
  console.debug("App dist exists, skipping build...")
}

// Generate embedded static assets module
let hasStaticAssets = false
const embeddedAssetsModule = path.join(dir, "src/server/costrict/embedded-assets.gen.ts")

try {
  const appDistGlob = path.join(appDir, "dist/**/*")
  const files = await glob(appDistGlob, { nodir: true })
  
  console.debug(`Found ${files.length} static assets, generating embedded module...`)
  
  // 生成包含所有静态资源的 TypeScript 模块
  const assets: Record<string, string> = {}
  for (const file of files) {
    const relativePath = path.relative(path.join(appDir, "dist"), file)
    const content = await fs.promises.readFile(file)
    const base64 = content.toString("base64")
    assets[relativePath] = base64
  }
  
  // 写入生成的模块文件
  const moduleContent = `// Auto-generated by build.ts - DO NOT EDIT
// Contains embedded static assets as base64 strings

export const EMBEDDED_ASSETS: Record<string, string> = ${JSON.stringify(assets, null, 2)};

export function getAssetBuffer(path: string): Buffer | null {
  const base64 = EMBEDDED_ASSETS[path];
  if (!base64) return null;
  return Buffer.from(base64, "base64");
}
`
  
  await fs.promises.writeFile(embeddedAssetsModule, moduleContent, "utf-8")
  hasStaticAssets = true
  console.debug(`Generated embedded assets module with ${Object.keys(assets).length} assets`)
} catch (error) {
  console.warn("Failed to generate embedded assets module:", error)
  // 创建空模块
  await fs.promises.writeFile(
    embeddedAssetsModule,
    `export const EMBEDDED_ASSETS: Record<string, string> = {};\nexport function getAssetBuffer(path: string): Buffer | null { return null; }\n`,
    "utf-8"
  )
}
/*costrict change end*/
// Generate builtin agents file before building
console.log("Generating builtin agents...")
await $`bun run script/generate-agents.ts`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"
  const callGraphWorkerPath = "./src/costrict/tool/call-graph/worker.ts"
  const fileImportanceWorkerPath = "./src/costrict/tool/file-importance/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/costrict-cli`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: [
      "./src/index.ts",
      parserWorker,
      workerPath,
      callGraphWorkerPath,
      fileImportanceWorkerPath,
      /*costrict change: static assets are now embedded in embedded-assets.gen.ts*/
    ],
    define: {
      COSTRICT_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      COSTRICT_WORKER_PATH: workerPath,
      COSTRICT_CALL_GRAPH_WORKER_PATH: callGraphWorkerPath,
      COSTRICT_FILE_IMPORTANCE_WORKER_PATH: fileImportanceWorkerPath,
      COSTRICT_CHANNEL: `'${Script.channel}'`,
      COSTRICT_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      EMBEDDED_APP_AVAILABLE: hasStaticAssets ? "true" : "false", /*costrict change*/
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

export { binaries }
