export namespace Flag {
  export const COSTRICT_AUTO_SHARE = truthy("COSTRICT_AUTO_SHARE")
  export const COSTRICT_GIT_BASH_PATH = process.env["COSTRICT_GIT_BASH_PATH"]
  export const COSTRICT_CONFIG = process.env["COSTRICT_CONFIG"]
  export const COSTRICT_CONFIG_DIR = process.env["COSTRICT_CONFIG_DIR"]
  export const COSTRICT_CONFIG_CONTENT = process.env["COSTRICT_CONFIG_CONTENT"]
  export const COSTRICT_DISABLE_AUTOUPDATE = truthy("COSTRICT_DISABLE_AUTOUPDATE")
  export const COSTRICT_DISABLE_PRUNE = truthy("COSTRICT_DISABLE_PRUNE")
  export const COSTRICT_DISABLE_TERMINAL_TITLE = truthy("COSTRICT_DISABLE_TERMINAL_TITLE")
  export const COSTRICT_PERMISSION = process.env["COSTRICT_PERMISSION"]
  export const COSTRICT_DISABLE_DEFAULT_PLUGINS = truthy("COSTRICT_DISABLE_DEFAULT_PLUGINS")
  export const COSTRICT_DISABLE_LSP_DOWNLOAD = truthy("COSTRICT_DISABLE_LSP_DOWNLOAD")
  export const COSTRICT_ENABLE_EXPERIMENTAL_MODELS = truthy("COSTRICT_ENABLE_EXPERIMENTAL_MODELS")
  export const COSTRICT_DISABLE_AUTOCOMPACT = truthy("COSTRICT_DISABLE_AUTOCOMPACT")
  export const COSTRICT_DISABLE_MODELS_FETCH = truthy("COSTRICT_DISABLE_MODELS_FETCH")
  export const COSTRICT_DISABLE_CLAUDE_CODE = truthy("COSTRICT_DISABLE_CLAUDE_CODE")
  export const COSTRICT_DISABLE_CLAUDE_CODE_PROMPT =
    COSTRICT_DISABLE_CLAUDE_CODE || truthy("COSTRICT_DISABLE_CLAUDE_CODE_PROMPT")
  export const COSTRICT_DISABLE_CLAUDE_CODE_SKILLS =
    COSTRICT_DISABLE_CLAUDE_CODE || truthy("COSTRICT_DISABLE_CLAUDE_CODE_SKILLS")
  export const COSTRICT_FAKE_VCS = process.env["COSTRICT_FAKE_VCS"]
  export const COSTRICT_CLIENT = process.env["COSTRICT_CLIENT"] ?? "cli"
  export const COSTRICT_SERVER_PASSWORD = process.env["COSTRICT_SERVER_PASSWORD"]
  export const COSTRICT_SERVER_USERNAME = process.env["COSTRICT_SERVER_USERNAME"]
  export const COSTRICT_APP_URL = process.env["COSTRICT_APP_URL"] ?? "https://app.opencode.ai"

  // Experimental
  export const COSTRICT_EXPERIMENTAL = truthy("COSTRICT_EXPERIMENTAL")
  export const COSTRICT_EXPERIMENTAL_FILEWATCHER = truthy("COSTRICT_EXPERIMENTAL_FILEWATCHER")
  export const COSTRICT_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("COSTRICT_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const COSTRICT_EXPERIMENTAL_ICON_DISCOVERY =
    COSTRICT_EXPERIMENTAL || truthy("COSTRICT_EXPERIMENTAL_ICON_DISCOVERY")
  export const COSTRICT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("COSTRICT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const COSTRICT_ENABLE_EXA =
    truthy("COSTRICT_ENABLE_EXA") || COSTRICT_EXPERIMENTAL || truthy("COSTRICT_EXPERIMENTAL_EXA")
  export const COSTRICT_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("COSTRICT_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const COSTRICT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("COSTRICT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const COSTRICT_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("COSTRICT_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const COSTRICT_EXPERIMENTAL_OXFMT = COSTRICT_EXPERIMENTAL || truthy("COSTRICT_EXPERIMENTAL_OXFMT")
  export const COSTRICT_EXPERIMENTAL_LSP_TY = truthy("COSTRICT_EXPERIMENTAL_LSP_TY")
  export const COSTRICT_EXPERIMENTAL_LSP_TOOL = COSTRICT_EXPERIMENTAL || truthy("COSTRICT_EXPERIMENTAL_LSP_TOOL")
  export const COSTRICT_EXPERIMENTAL_PLAN_MODE = COSTRICT_EXPERIMENTAL || truthy("COSTRICT_EXPERIMENTAL_PLAN_MODE")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
