// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

import AGENT_0 from "./task-check.txt"
import AGENT_1 from "./sub-coding.txt"
import AGENT_2 from "./strict-plan.txt"
import AGENT_3 from "./tdd.txt"
import AGENT_4 from "./coding.txt"
import AGENT_5 from "./quick-explore.txt"
import AGENT_6 from "./fix-agent.txt"

// Wiki agents - hidden subagents for project-wiki command
import WIKI_01 from "./wiki/01-project-analyze.txt"
import WIKI_02 from "./wiki/02-catalogue-design.txt"
import WIKI_03 from "./wiki/03-document-generate.txt"
import WIKI_04 from "./wiki/04-index-generation.txt"

export const BUILTIN_AGENTS = [
  AGENT_0,
  AGENT_1,
  AGENT_2,
  AGENT_3,
  AGENT_4,
  AGENT_5,
  AGENT_6,
  WIKI_01,
  WIKI_02,
  WIKI_03,
  WIKI_04
]
