// This file is auto-generated by script/generate-agents.ts
// Do not edit manually

import AGENT_0 from "./builtin/fix-agent.txt"
import AGENT_1 from "./builtin/plan_apply.txt"
import AGENT_2 from "./builtin/quick_explore.txt"
import AGENT_3 from "./builtin/strict-plan.txt"
import AGENT_4 from "./builtin/test_and_fix.txt"
import AGENT_5 from "./builtin/test_design.txt"

export const BUILTIN_AGENTS = [
  AGENT_0,
  AGENT_1,
  AGENT_2,
  AGENT_3,
  AGENT_4,
  AGENT_5
]
